### ISSUE TITLE
Fix aspect ratio of scanner view on menu screen

### ISSUE THREAD

**Issue by rjvince** [pauljstales/nolongeralone#117]
The enemy has induced a time window anomaly in Sector 17. The resulting gravitational lens effect has squished the output of the deep space scanner. Please adjust the Constants of Scaled Space (CSS) to adapt to the new shape of relative dimensions.

**Comment by pauljstales** [comment]
Constants of Scaled Space adjusted to only affect the horizontal dimensions - relative to vertical! Those damn aliens _should_ not be able to reproduce this, no matter what hardware or they use, big screen, little screen, ANY SCREEN!
