### ISSUE TITLE
MUSIC - All Soundtracks

### ISSUE THREAD

**Issue by pauljstales** [pauljstales/nolongeralone#94]
@rjvince 

updated for 2021-05-04

Figured I'd consolidate some tickets to make the issues less of a sea of random stuff.
All possible soundtracks would be as follows _(if you wanted to do them, of course)_

1 landing screen - no music - DONE
2 intro screen - music written - DONE
3 menu screen - music written - DONE
4 tutorial screen - using same as menu - DONE
5 battle screen - music written - DONE
6 credits/gameover - both win and loss - DONE

unless you have anymore ideas for music, I would say the music is done

**Comment by pauljstales** [comment]
Music is again available as of 2021-04-27, https://nla.netlify.app

**Comment by rjvince** [comment]
Re: 6, adding music for victory

**Comment by rjvince** [comment]
Re: 4, I think the tutorial screen should use the menu music.

**Comment by pauljstales** [comment]
> Re: 4, I think the tutorial screen should use the menu music.
pushed

**Comment by pauljstales** [comment]
unless you have anymore ideas for music, I would say the music is done
